# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages:
  - stage: Build
    jobs:
    - job: Build
      pool:
        vmImage: 'ubuntu-latest'

      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

      - task: Npm@1
        displayName: NPM Install
        inputs:
          command: 'install'
          workingDir: 'nodejs-docs-hello-world-master'

      - task: Npm@1
        displayName: NPM Build
        inputs:
          command: 'custom'
          workingDir: 'nodejs-docs-hello-world-master'
          customCommand: 'build'
  
